server:
  port: 8083

spring:
  application:
    name: servicio-notificaciones
  datasource:
    url: jdbc:h2:mem:notificaciones_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    #url: jdbc:postgresql://localhost:5432/notificaciones_db
    #username: postgres
    #password: qwerty123
    #url: jdbc:postgresql://localhost:26257/notificaciones_db?user=root&password=
    #username: root
    #password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

