# Eureka Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sistema-agricola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: sistema-agricola/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: sistema-agricola
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
  type: NodePort
---
# API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sistema-agricola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: sistema-agricola/api-gateway:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sistema-agricola
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort
---
# Microservicio de Agricultura (api-publicaciones)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agricultura
  namespace: sistema-agricola
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agricultura
  template:
    metadata:
      labels:
        app: agricultura
    spec:
      containers:
        - name: agricultura
          image: sistema-agricola/agricultura:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/agricultura"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: agricultura
  namespace: sistema-agricola
spec:
  selector:
    app: agricultura
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Microservicio de Inventario
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario
  namespace: sistema-agricola
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventario
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
        - name: inventario
          image: sistema-agricola/inventario:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/inventario"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: inventario
  namespace: sistema-agricola
spec:
  selector:
    app: inventario
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
# Microservicio de Facturación
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facturacion
  namespace: sistema-agricola
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facturacion
  template:
    metadata:
      labels:
        app: facturacion
    spec:
      containers:
        - name: facturacion
          image: sistema-agricola/facturacion:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mariadb:3306/facturacion"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: facturacion
  namespace: sistema-agricola
spec:
  selector:
    app: facturacion
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
---
# Microservicio de Notificaciones
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones
  namespace: sistema-agricola
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
        - name: notificaciones
          image: sistema-agricola/notificaciones:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/notificaciones"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: notificaciones
  namespace: sistema-agricola
spec:
  selector:
    app: notificaciones
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP

