apiVersion: v1
kind: Namespace
metadata:
  name: ejemplo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ejemplo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: calderonperaza/ejemplobackend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/ejemplo
#              value: mongodb+srv://backend:mongo12345@sandbox.ofd4p.mongodb.net/ejemplo?retryWrites=true&w=majority
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: ejemplo
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
#Se puede exponer en un ingress usando un dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: ejemplo
spec:
  rules:
    - host: backend.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
#se debe agregar el dominio en /etc/host
#sudo bash -c "echo $(minikube ip) backend.io frontend.io >> /etc/hosts"